version: "3"

services:
  mysql:
    image: pavansrivathsa/mysql
    command: 
      - '--default-authentication-plugin=mysql_native_password'
      - '--local-infile=1'
    restart: always
    ports:
        - 3306:3306
        - 33060:33060    
    volumes:
      - mysql_data:/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: example
    container_name: ra_mysql
  adminer:
    image: adminer
    restart: always
    ports:
        - 1001:8080
volumes:
  mysql_data: